{% set name = "nagl" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 2fd19cac15ca232ef6463d5ac5a8d620c2ef6f7e67873f87c471fea7ac021ab1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - nagl = nagl.cli:cli

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - openff-utilities
    - pydantic
    - click
    - click-option-group
    - pytorch
    - tqdm
    - sqlalchemy

test:
  imports:
    - nagl
  commands:
    - nagl --help

about:
  home: https://github.com/SimonBoothroyd/nagl
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE-3RD-PARTY
  summary: A playground for applying graph convolutional networks to molecules.
  description: |
    A playground for applying graph convolutional networks to molecules, with a focus 
    on learning continuous "atom-type" embeddings and from these classical molecule 
    force field parameters.
  doc_url: https://github.com/SimonBoothroyd/nagl
  dev_url: https://github.com/SimonBoothroyd/nagl

extra:
  recipe-maintainers:
    - simonboothroyd
